[package]
name = "v8_valueserializer"
version = "0.1.0"
edition = "2021"

[dependencies]
indexmap = "2.0.2"
insta = "1.34.0"
num-bigint = "0.4.4"
rand = "0.8.5"
thiserror = "1.0.49"

[dev-dependencies]
v8 = "0.79.2"
